name: morning
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your friend

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: sender
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - run: pip install -r ./requirements.txt && python ./main.py

    env:
      CITYS: ${{ secrets.CITYS }}
      WEBHOOK: ${{ secrets.WEBHOOK }}
      QIAN: ${{ secrets.QIAN }}
      ANNOS: ${{ secrets.ANNOS }}